#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Data models for the kie.ai SDK.

A :class:`Catalog` is built from ``catalog.json`` (generated by
``build_catalog.py``).  Each :class:`ModelEntry` describes one API method:
which endpoint to call, how to build the request body, which endpoint to poll
for results, and which parameters the model accepts.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from .exceptions import KieModelNotFound


@dataclass
class Param:
    name: str
    type: str = "string"
    required: bool = False
    default: Any = None
    enum: Optional[List[Any]] = None
    description: str = ""

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "Param":
        return cls(
            name=d["name"],
            type=d.get("type", "string"),
            required=bool(d.get("required", False)),
            default=d.get("default"),
            enum=d.get("enum"),
            description=d.get("description", ""),
        )


@dataclass
class ModelEntry:
    id: str
    name: str
    platform: str
    category: str
    family: str
    request_style: str
    endpoint: str
    poll_endpoint: Optional[str]
    poll_id_param: Optional[str]
    model_ref: Optional[str] = None
    model_options: Optional[List[str]] = None
    description: str = ""
    method: str = "POST"
    params: List[Param] = field(default_factory=list)
    model_date: str = "N/A"
    official_price: str = "N/A"
    kie_price: str = "N/A"
    other_info_url: str = "https://kie.ai/pricing"
    doc_url: str = ""
    pricing: Optional[Dict[str, Any]] = None

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "ModelEntry":
        return cls(
            id=d["id"],
            name=d.get("name", d["id"]),
            platform=d.get("platform", ""),
            category=d.get("category", ""),
            family=d.get("family", ""),
            request_style=d.get("request_style", "direct"),
            endpoint=d["endpoint"],
            poll_endpoint=d.get("poll_endpoint"),
            poll_id_param=d.get("poll_id_param"),
            model_ref=d.get("model_ref"),
            model_options=d.get("model_options"),
            description=d.get("description", ""),
            method=d.get("method", "POST"),
            params=[Param.from_dict(p) for p in d.get("params", [])],
            model_date=d.get("model_date", "N/A"),
            official_price=d.get("official_price", "N/A"),
            kie_price=d.get("kie_price", "N/A"),
            other_info_url=d.get("other_info_url", "https://kie.ai/pricing"),
            doc_url=d.get("doc_url", ""),
            pricing=d.get("pricing"),
        )

    # ------------------------------------------------------------------ #
    def build_body(self, params: Dict[str, Any]) -> Dict[str, Any]:
        """Build the JSON request body for this model from user kwargs."""
        if self.request_style == "market":
            # Market models: { "model": <model_ref>, "input": { <params> } }
            body: Dict[str, Any] = {"model": self.model_ref, "input": dict(params)}
            return body
        # direct / upload: parameters go straight to the top level
        body = dict(params)
        if self.model_options and "model" not in body:
            # honour the model selector's cataloged default, if any
            default_model = None
            for p in self.params:
                if p.name == "model" and p.default is not None:
                    default_model = p.default
                    break
            body["model"] = default_model or self.model_options[0]
        return body

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "name": self.name,
            "platform": self.platform,
            "category": self.category,
            "family": self.family,
            "request_style": self.request_style,
            "endpoint": self.endpoint,
            "poll_endpoint": self.poll_endpoint,
            "poll_id_param": self.poll_id_param,
            "model_ref": self.model_ref,
            "model_options": self.model_options,
            "description": self.description,
            "params": [vars(p) for p in self.params],
            "model_date": self.model_date,
            "official_price": self.official_price,
            "kie_price": self.kie_price,
            "other_info_url": self.other_info_url,
            "doc_url": self.doc_url,
            "pricing": self.pricing,
        }


class Catalog:
    """In-memory index of all :class:`ModelEntry` objects."""

    def __init__(self, data: Dict[str, Any]):
        self.raw = data
        self.models: List[ModelEntry] = [
            ModelEntry.from_dict(m) for m in data.get("models", [])
        ]
        self.families = data.get("families", {})
        self._by_id: Dict[str, ModelEntry] = {}
        self._by_ref: Dict[str, ModelEntry] = {}
        for m in self.models:
            self._by_id[m.id] = m
            if m.model_ref:
                self._by_ref[m.model_ref] = m

    # ------------------------------------------------------------------ #
    @classmethod
    def load(cls, path: Optional[str] = None) -> "Catalog":
        if path is None:
            path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "catalog.json")
        with open(path, "r", encoding="utf-8") as fh:
            inst = cls(json.load(fh))
            inst._path = path
            return inst

    def save(self, path: Optional[str] = None) -> None:
        path = path or getattr(self, "_path", None)
        if path is None:
            raise ValueError("No path specified and catalog was not loaded from a file")
        out = dict(self.raw)
        out["models"] = [m.to_dict() for m in self.models]
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(out, fh, ensure_ascii=False, indent=2)

    def get(self, key: str) -> ModelEntry:
        """Resolve a model by id, model_ref, or (case-insensitive) name."""
        if key in self._by_id:
            return self._by_id[key]
        if key in self._by_ref:
            return self._by_ref[key]
        low = key.lower()
        for m in self.models:
            if m.name.lower() == low or m.id.lower() == low:
                return m
        for m in self.models:
            if low in m.name.lower():
                return m
        raise KieModelNotFound(f"Model not found: {key!r}")

    def search(
        self,
        category: Optional[str] = None,
        family: Optional[str] = None,
        platform: Optional[str] = None,
        query: Optional[str] = None,
    ) -> List[ModelEntry]:
        out = []
        q = query.lower() if query else None
        for m in self.models:
            if category and m.category != category:
                continue
            if family and m.family != family:
                continue
            if platform and m.platform.lower() != platform.lower():
                continue
            if q and q not in m.name.lower() and q not in m.id.lower():
                continue
            out.append(m)
        return out

    def __len__(self) -> int:
        return len(self.models)
