/**
 * Language dictionary for source/target language selection.
 * Key: language code, Value: display name (Chinese).
 */
export const LANGUAGES: Record<string, string> = {
  auto: "自动检测",
  // === 中文 ===
  zh: "中文（普通话）",
  "zh-yue-hk": "粤语（香港口音）",
  "zh-yue-gd": "粤语（广东口音）",
  "zh-wuu": "吴语",
  "zh-min": "闽南语",
  "zh-anhui": "安徽话",
  "zh-dongbei": "东北话",
  "zh-fujian": "福建话",
  "zh-gansu": "甘肃话",
  "zh-guizhou": "贵州话",
  "zh-hebei": "河北话",
  "zh-henan": "河南话",
  "zh-hubei": "湖北话",
  "zh-hunan": "湖南话",
  "zh-jiangxi": "江西话",
  "zh-ningxia": "宁夏话",
  "zh-shandong": "山东话",
  "zh-shaanxi": "陕西话",
  "zh-shanxi": "山西话",
  "zh-sichuan": "四川话",
  "zh-tianjin": "天津话",
  "zh-yunnan": "云南话",
  "zh-zhejiang": "浙江话",
  // === 主要语言 ===
  en: "英语",
  ja: "日语",
  ko: "韩语",
  fr: "法语",
  de: "德语",
  es: "西班牙语",
  pt: "葡萄牙语",
  ru: "俄语",
  ar: "阿拉伯语",
  it: "意大利语",
  nl: "荷兰语",
  pl: "波兰语",
  tr: "土耳其语",
  vi: "越南语",
  th: "泰语",
  id: "印尼语",
  hi: "印地语",
  ms: "马来语",
  // === 北欧语言 ===
  sv: "瑞典语",
  da: "丹麦语",
  fi: "芬兰语",
  no: "挪威语",
  // === 中东欧语言 ===
  cs: "捷克语",
  el: "希腊语",
  he: "希伯来语",
  hu: "匈牙利语",
  ro: "罗马尼亚语",
  uk: "乌克兰语",
  // === 其他语言 ===
  bn: "孟加拉语",
  fa: "波斯语",
  tl: "菲律宾语",
  mk: "马其顿语",
  ca: "加泰罗尼亚语",
  sk: "斯洛伐克语",
  hr: "克罗地亚语",
  bg: "保加利亚语",
  lt: "立陶宛语",
  lv: "拉脱维亚语",
  et: "爱沙尼亚语",
  sl: "斯洛文尼亚语",
  sr: "塞尔维亚语",
  nb: "挪威语（书面）",
};

export const LANGUAGE_OPTIONS = Object.entries(LANGUAGES).map(([value, label]) => ({
  value,
  label: value === "auto" ? `${label} (auto)` : `${label} (${value})`,
}));